[package]
name = "image-pipeline"
version = "0.1.0"
authors = ["Brendon Walsh <brendonwalsh@niamu.com>"]
edition = "2021"

[dependencies]
image = "0.25"
rayon = "1.8"
webp = "0.3.0"
walkdir = "2.4"
log = "0.4"
env_logger = "0.11"
structopt = "0.3.26"
